"""
Compute RGB-SSIM between original TIFF images and approximated JPEG outputs.

This script compares a reference TIFF dataset against JPEG outputs generated
under approximate execution. It can recover valid JPEG payloads when the AxPike
output contains a crash dump after the image bytes.

Example usage:

python compute_jpeg_ssim.py \
  --perfect-dir /home/guilherme/Pictures/UCMerced_Split_Fixed \
  --error-dir /home/guilherme/Pictures/UC_MERCED_LAND_USE/dataset_error_rate_1e-2/src/dataset_error_rate_1e-2
"""

import argparse
import concurrent.futures
import io
import os
import re
from pathlib import Path

import numpy as np
from PIL import Image, ImageFile
from skimage.metrics import structural_similarity as ssim
from tqdm import tqdm


ImageFile.LOAD_TRUNCATED_IMAGES = True

PAYLOAD_MINIMO = 1024
MARCADORES_VALIDOS = [b"\xff\xe0", b"\xff\xe1", b"\xff\xdb"]

PADRAO_CRASH = re.compile(br"z\s+[0-9a-fA-F]{16}\s+ra\s+[0-9a-fA-F]{16}")


def resgatar_jpeg_antes_do_crash(caminho_arquivo):
    """
    Extract the valid JPEG payload from an AxPike output file.

    If the output contains a RISC-V crash dump after the image data, the file is
    truncated before the crash log. The remaining bytes are then validated using
    basic JPEG markers and a minimum payload size.
    """
    try:
        if os.path.getsize(caminho_arquivo) == 0:
            return None, "empty"

        with open(caminho_arquivo, "rb") as f:
            conteudo = f.read()

        match_crash = PADRAO_CRASH.search(conteudo)

        if match_crash:
            dados_validos = conteudo[:match_crash.start()]
            teve_crash = True
        else:
            dados_validos = conteudo
            teve_crash = False

        inicio_jpeg = dados_validos.find(b"\xff\xd8")

        if inicio_jpeg == -1:
            return None, "no_ffd8"

        payload = len(dados_validos) - inicio_jpeg - 2

        if payload < PAYLOAD_MINIMO:
            return None, "corrompida_payload_pequeno"

        janela = dados_validos[inicio_jpeg + 2:min(inicio_jpeg + 22, len(dados_validos))]

        if not any(m in janela for m in MARCADORES_VALIDOS):
            return None, "corrompida_sem_marcador"

        status = "rescued_crash" if teve_crash else "clean"
        return dados_validos[inicio_jpeg:], status

    except OSError:
        return None, "os_error"


def process_image_pair(args):
    """
    Process one original TIFF image and its corresponding approximated JPEG.

    The function attempts to recover valid JPEG bytes when the AxPike output
    contains crash information, loads both images, normalizes resolution when
    needed, and computes RGB-SSIM.
    """
    img_perfeita_file, error_path, perfect_path = args

    rel_path = img_perfeita_file.relative_to(perfect_path)

    img_erro_file = error_path / rel_path.with_suffix(".jpeg")

    if not img_erro_file.exists():
        img_erro_file = error_path / rel_path.with_suffix(".jpg")

    if not img_erro_file.exists():
        return "missing", 0

    bytes_imagem, status_binario = resgatar_jpeg_antes_do_crash(img_erro_file)

    if bytes_imagem is None:
        return status_binario, 0

    try:
        img_perf = Image.open(img_perfeita_file).convert("RGB")
        img_err = Image.open(io.BytesIO(bytes_imagem)).convert("RGB")

        np_perf = np.array(img_perf)
        np_err = np.array(img_err)

        if np_perf.shape != np_err.shape:
            img_err = img_err.resize((np_perf.shape[1], np_perf.shape[0]))
            np_err = np.array(img_err)

        score, _ = ssim(np_perf, np_err, channel_axis=-1, full=True)

        return status_binario, score

    except (OSError, SyntaxError, Image.UnidentifiedImageError):
        return "pil_rejected", 0


def calculate_dataset_ssim(perfect_dir, error_dir):
    """
    Compute the average RGB-SSIM between the original TIFF dataset and the
    approximated JPEG dataset generated by AxCept-Bench.
    """
    perfect_path = Path(perfect_dir)
    error_path = Path(error_dir)

    todas_perfeitas = sorted(perfect_path.rglob("*.tif"))
    tasks = [(f, error_path, perfect_path) for f in todas_perfeitas]

    print("Analyzing structural degradation: original TIFF vs recovered JPEG outputs...")

    ssim_scores = []

    stats = {
        "clean": 0,
        "rescued_crash": 0,
        "corrompida_payload_pequeno": 0,
        "corrompida_sem_marcador": 0,
        "no_ffd8": 0,
        "empty": 0,
        "pil_rejected": 0,
        "missing": 0,
        "os_error": 0,
    }

    with concurrent.futures.ProcessPoolExecutor() as executor:
        results = list(tqdm(executor.map(process_image_pair, tasks), total=len(tasks)))

    for status, score in results:
        stats[status] = stats.get(status, 0) + 1

        if status in ["clean", "rescued_crash"]:
            ssim_scores.append(score)

    media_final = np.mean(ssim_scores) if ssim_scores else 0.0
    total_validas = stats["clean"] + stats["rescued_crash"]

    print("\n" + "=" * 60)
    print("STRUCTURAL DEGRADATION REPORT (SSIM WITH JPEG RECOVERY)")
    print("=" * 60)
    print(f"  Valid outputs (clean)        : {stats['clean']}")
    print(f"  Valid outputs (rescued)      : \033[96m{stats['rescued_crash']}\033[0m")
    print("-" * 60)
    print(f"  Total used for SSIM          : {total_validas}")
    print("-" * 60)
    print(f"  Discarded (< 1 KB payload)   : {stats['corrompida_payload_pequeno']}")
    print(f"  Discarded (missing marker)   : {stats['corrompida_sem_marcador']}")
    print(f"  Discarded (missing FFD8)     : {stats['no_ffd8']}")
    print(f"  Discarded (PIL rejected)     : {stats['pil_rejected']}")
    print(f"  Empty outputs / timeout      : {stats['empty']}")
    print(f"  Missing outputs              : \033[93m{stats['missing']}\033[0m")
    print("=" * 60)
    print(f"  GLOBAL AVERAGE SSIM          : \033[92m{media_final:.4f}\033[0m")
    print("=" * 60)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Compute RGB-SSIM between original TIFF images and approximated JPEG outputs."
    )

    parser.add_argument(
        "--perfect-dir",
        required=True,
        help="Path to the original TIFF dataset.",
    )

    parser.add_argument(
        "--error-dir",
        required=True,
        help="Path to the approximated JPEG dataset generated by AxCept-Bench.",
    )

    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    calculate_dataset_ssim(args.perfect_dir, args.error_dir)
